export const placeholders = [
    "¿Qué es el hostigamiento sexual?",
    "Prevención y sanción del acoso sexual",
    "Unidad Politécnica de Gestión con Perspectiva de Género",
    "Compromiso político contra la violencia",
    "Violencia contra las mujeres: ¿Cómo se define?",
    "Procedimientos para la gestión con perspectiva de género",
    "Protocolos de equidad de género",
    "¿Cómo prevenir el acoso sexual?",
    "Atención a víctimas de violencia de género",
    "Definición de hostigamiento y acoso sexual",
]

export const placeholder_search = [
    "Gestión de becas escolares",
    "Programas de apoyo educativo",
    "Lenguaje inclusivo y no sexista",
    "Promover comunicación equitativa",
    "Comunicados oficiales",
    "Noticias y avances académicos",
    "Convocatorias culturales vigentes",
    "Concursos y festivales de arte",
    "Convocatorias deportivas",
    "Participación en competencias deportivas",
    "Consulta de la Gaceta",
    "Avances académicos y convocatorias",
    "Protocolos de equidad de género",
    "Derechos de género",
    "Manual de identidad gráfica",
    "Lineamientos gráficos del IPN",
    "Normativas y reglamentos vigentes",
    "Funcionamiento del IPN",
]
